// Photography albums: one per shoot folder on the photo drive, kept in the
// `albums` content collection (src/content/albums/*.yaml, generated by
// `npm run photos:albums -- build`). The photos themselves are read from
// Cloudinary by id (api/cloudinary/album), so nothing is tagged there.
import { getCollection } from "astro:content";
import { CLOUD_NAME } from "./cloudinary";
import { cloudinaryTransform } from "./cloudinaryImage";

export type Album = {
  slug: string;
  title: string;
  /** `YYYY-MM-DD`, or null when nothing in the album is dated (label shows the year). */
  date: string | null;
  year: number;
  count: number;
  /** Cloudinary public_ids, in capture order. Server-only: never sent to the island. */
  photos: string[];
};

export const MIN_ALBUM_PHOTOS = 5;

/** Shown albums (≥ MIN_ALBUM_PHOTOS), newest first (undated ones as January 1st of their year). */
export async function listAlbums(): Promise<Album[]> {
  const entries = await getCollection("albums");
  return entries
    .map(({ id, data }) => ({ ...data, slug: id, date: data.date ? data.date.toISOString().slice(0, 10) : null }))
    .filter((album) => album.count >= MIN_ALBUM_PHOTOS)
    .sort((a, b) => (b.date ?? `${b.year}-01-01`).localeCompare(a.date ?? `${a.year}-01-01`) || a.title.localeCompare(b.title));
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/** Stack label: `May 2026 · 24 photos`, or `2024 · 12 photos` when undated. */
export function albumDetails({ date, year, count }: Pick<Album, "date" | "year" | "count">): string {
  const when = date ? `${MONTHS[Number(date.slice(5, 7)) - 1]} ${date.slice(0, 4)}` : String(year);
  return `${when} · ${count} ${count === 1 ? "photo" : "photos"}`;
}

/** One stack card's photo: a single crop at 2× the 176×220 card. The
 *  carousel can hold every album, so a card costs one ~20KB image and a URL,
 *  not a srcset. Center crop, the same framing as the explode flyer's
 *  object-fit: cover, so the photo doesn't jump as the card leaves. */
export type StackPhoto = { key: string; src: string };

const STACK_CARD_TRANSFORM = "c_fill,w_352,h_440,f_auto,q_auto";

export const toStackPhoto = (publicId: string, cloudName = CLOUD_NAME): StackPhoto => ({
  key: publicId,
  src: cloudinaryTransform(`https://res.cloudinary.com/${cloudName}/image/upload/${publicId}`, STACK_CARD_TRANSFORM),
});

/** What the album carousel island receives: label text and the stack's card
 *  photos, computed on the server. `previews[0]` is the top card. */
export type AlbumCard = {
  slug: string;
  title: string;
  details: string;
  previews: StackPhoto[];
};

export const toAlbumCard = (album: Album): AlbumCard => ({
  slug: album.slug,
  title: album.title,
  details: albumDetails(album),
  previews: album.photos.slice(0, 3).map((id) => toStackPhoto(id)),
});
